export enum Path {
    HOME = '/',
    SIGN_IN = '/auth/signin',
    SIGN_UP = '/auth/signup',
    ERROR_LOGIN = '/result/error-login',
    RESULT_SUCCESS = '/result/success',
    USER_EXIST = '/result/error-user-exist',
    ERROR = '/result/error',
    ERROR_CHECK_EMAIL_NO_EXIST = '/result/error-check-email-no-exist',
    ERROR_CHECK_EMAIL = '/result/error-check-email',
    CONFIRM_EMAIL = '/auth/confirm-email',
    CHANGE_PASSWORD = '/auth/change-password',
    ERROR_CHANGE_PASSWORD = '/result/error-change-password',
    SUCESS_CHANGE_PASSWORD = '/result/success-change-password',
}
